/**
 * MockApiClient: offline fixtures for the full UI surface.
 *
 * One scene per SceneStatus so every list/detail/viewer state is reachable
 * with no backend and no auth. The ready scene's assets reference local
 * files under /dev-fixtures/ (generated by tools/make_synthetic_splat.py,
 * gitignored) through the same manifest-v2 + asset_urls shapes the live
 * endpoint returns — the viewer cannot tell the difference.
 */

import { ApiError, SceneNotReadyError, type ApiClient } from "./client";
import type { SceneAssets, SceneStatus, SceneSummary } from "./types";

/** Fixed UUIDs so deep links are stable across reloads. */
export const MOCK_READY_SCENE_ID = "11111111-1111-4111-8111-111111111111";

const STATUS_FIXTURES: Array<{ status: SceneStatus; minutesAgo: number }> = [
  { status: "ready", minutesAgo: 30 },
  { status: "processing", minutesAgo: 4 },
  { status: "queued", minutesAgo: 1 },
  { status: "failed_incomplete", minutesAgo: 90 },
  { status: "failed_invalid", minutesAgo: 200 },
  { status: "failed", minutesAgo: 400 },
];

function sceneFixture(idx: number, status: SceneStatus, minutesAgo: number): SceneSummary {
  const n = (idx + 1).toString().repeat(8).slice(0, 8);
  const sceneId =
    status === "ready" ? MOCK_READY_SCENE_ID : `${n}-1111-4111-8111-111111111111`;
  const t = new Date(Date.now() - minutesAgo * 60_000).toISOString();
  return {
    scene_id: sceneId,
    bundle_id: `${n}-2222-4222-8222-222222222222`,
    status,
    result_uri:
      status === "ready" ? `gs://mock-outputs/scenes/${sceneId}/manifest.json` : null,
    missing_paths:
      status === "failed_incomplete" ? ["frames/000004.jpg", "frames/000007.jpg"] : null,
    created_at: t,
    updated_at: t,
  };
}

const GS = (name: string) =>
  `gs://mock-outputs/scenes/${MOCK_READY_SCENE_ID}/splats/${name}.ply`;

/** A small synthetic room: objects placed around the origin, +Y up. */
const READY_ASSETS: SceneAssets = {
  scene_id: MOCK_READY_SCENE_ID,
  manifest: {
    scene_id: MOCK_READY_SCENE_ID,
    manifest_version: 2,
    objects: [
      {
        object_id: "obj_000",
        label: "sofa",
        placed: true,
        method: "depth_fit",
        splat_gcs_uri: GS("sofa"),
        world_transform: {
          position: [0, 0.35, -1.6],
          rotation_xyzw: [0, 0, 0, 1],
          scale: 1.4,
        },
      },
      {
        object_id: "obj_001",
        label: "table",
        placed: true,
        method: "depth_fit",
        splat_gcs_uri: GS("table"),
        world_transform: {
          position: [0.1, 0.25, -0.4],
          rotation_xyzw: [0, 0.3826834, 0, 0.9238795], // 45 deg about +Y
          scale: 0.9,
        },
      },
      {
        object_id: "obj_002",
        label: "lamp",
        placed: true,
        method: "layout_triangulated",
        splat_gcs_uri: GS("lamp"),
        world_transform: {
          position: [-1.2, 0.8, -1.2],
          rotation_xyzw: [0, 0, 0, 1],
          scale: 0.5,
        },
      },
      {
        object_id: "obj_003",
        label: "plant",
        placed: false,
        method: null,
        reason: "insufficient_observations",
        splat_gcs_uri: GS("plant"),
        world_transform: null,
      },
    ],
    frames: [],
  },
  asset_urls: {
    [GS("sofa")]: "/dev-fixtures/sofa.ply",
    [GS("table")]: "/dev-fixtures/table.ply",
    [GS("lamp")]: "/dev-fixtures/lamp.ply",
  },
  expires_at: new Date(Date.now() + 3600_000).toISOString(),
};

const LATENCY_MS = 250;

function delay<T>(value: T): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), LATENCY_MS));
}

export class MockApiClient implements ApiClient {
  readonly scenes = STATUS_FIXTURES.map((f, i) => sceneFixture(i, f.status, f.minutesAgo));

  async listScenes(limit = 50): Promise<SceneSummary[]> {
    const sorted = [...this.scenes].sort((a, b) =>
      b.created_at.localeCompare(a.created_at),
    );
    return delay(sorted.slice(0, limit));
  }

  async getSceneByBundle(bundleId: string): Promise<SceneSummary> {
    const scene = this.scenes.find((s) => s.bundle_id === bundleId);
    if (!scene) {
      throw new ApiError(404, "not_found", `No scene for bundle ${bundleId}`);
    }
    return delay(scene);
  }

  async getSceneAssets(sceneId: string): Promise<SceneAssets> {
    const scene = this.scenes.find((s) => s.scene_id === sceneId);
    if (!scene) {
      throw new ApiError(404, "not_found", `No scene ${sceneId}`);
    }
    if (scene.status !== "ready") {
      throw new SceneNotReadyError(scene.status);
    }
    return delay(READY_ASSETS);
  }
}
