/**
 * MockApiClient: offline fixtures for the full UI surface.
 *
 * One scene per SceneStatus so every list/detail/viewer state is reachable
 * with no backend and no auth. The ready scene's assets reference local
 * files under /dev-fixtures/ (generated by tools/make_synthetic_splat.py,
 * gitignored) through the same manifest-v2 + asset_urls shapes the live
 * endpoint returns — the viewer cannot tell the difference.
 */

import {
  ApiError,
  BudgetExhaustedError,
  SceneNotReadyError,
  TurnInFlightError,
  type ApiClient,
} from "./client";
import type {
  ConversationSnapshot,
  ConversationTurn,
  GuestEvent,
  SceneAssets,
  SceneStatus,
  SceneSummary,
} from "./types";

/** Fixed UUIDs so deep links are stable across reloads. */
export const MOCK_READY_SCENE_ID = "11111111-1111-4111-8111-111111111111";

const STATUS_FIXTURES: Array<{ status: SceneStatus; minutesAgo: number }> = [
  { status: "ready", minutesAgo: 30 },
  { status: "processing", minutesAgo: 4 },
  { status: "queued", minutesAgo: 1 },
  { status: "failed_incomplete", minutesAgo: 90 },
  { status: "failed_invalid", minutesAgo: 200 },
  { status: "failed", minutesAgo: 400 },
];

function sceneFixture(idx: number, status: SceneStatus, minutesAgo: number): SceneSummary {
  const n = (idx + 1).toString().repeat(8).slice(0, 8);
  const sceneId =
    status === "ready" ? MOCK_READY_SCENE_ID : `${n}-1111-4111-8111-111111111111`;
  const t = new Date(Date.now() - minutesAgo * 60_000).toISOString();
  return {
    scene_id: sceneId,
    bundle_id: `${n}-2222-4222-8222-222222222222`,
    status,
    result_uri:
      status === "ready" ? `gs://mock-outputs/scenes/${sceneId}/manifest.json` : null,
    missing_paths:
      status === "failed_incomplete" ? ["frames/000004.jpg", "frames/000007.jpg"] : null,
    created_at: t,
    updated_at: t,
  };
}

const GS = (name: string) =>
  `gs://mock-outputs/scenes/${MOCK_READY_SCENE_ID}/splats/${name}.ply`;

/** A shell.json v2 material {} (decision 0069). */
function mockMaterial(
  family: string | null,
  albedo: string | null,
  roughness: number,
  observed: number,
): import("./types").ShellMaterialEntry {
  return {
    family,
    family_confidence: family ? 0.82 : null,
    albedo_hex: albedo,
    secondary_hex: null,
    params: family === "wood" ? { plank_direction_deg: 90 } : {},
    render: { roughness },
    source: {
      observed_fraction: observed,
      texel_count: Math.round(observed * 12000),
      frames_used: observed > 0 ? 6 : 0,
    },
    inference: {
      model: family ? "claude-sonnet-5" : null,
      material_version: 1,
    },
  };
}

/** A small synthetic room: objects placed around the origin, +Y up. */
const READY_ASSETS: SceneAssets = {
  scene_id: MOCK_READY_SCENE_ID,
  manifest: {
    scene_id: MOCK_READY_SCENE_ID,
    manifest_version: 2,
    objects: [
      {
        object_id: "obj_000",
        label: "sofa",
        placed: true,
        method: "depth_fit",
        splat_gcs_uri: GS("sofa"),
        world_transform: {
          position: [0, 0.35, -1.6],
          rotation_xyzw: [0, 0, 0, 1],
          scale: 1.4,
        },
      },
      {
        object_id: "obj_001",
        label: "table",
        placed: true,
        method: "depth_fit",
        splat_gcs_uri: GS("table"),
        world_transform: {
          position: [0.1, 0.25, -0.4],
          rotation_xyzw: [0, 0.3826834, 0, 0.9238795], // 45 deg about +Y
          scale: 0.9,
        },
      },
      {
        object_id: "obj_002",
        label: "lamp",
        placed: true,
        method: "layout_triangulated",
        splat_gcs_uri: GS("lamp"),
        world_transform: {
          position: [-1.2, 0.8, -1.2],
          rotation_xyzw: [0, 0, 0, 1],
          scale: 0.5,
        },
      },
      {
        object_id: "obj_003",
        label: "plant",
        placed: false,
        method: null,
        reason: "insufficient_observations",
        splat_gcs_uri: GS("plant"),
        world_transform: null,
      },
    ],
    frames: [],
  },
  // Room shell v2 (decision 0069): parametric materials, no textures.
  // The floor is an L-ish polygon (exercises triangulation); wall_00
  // carries a door opening + closure provenance; wall_01 ships fully
  // UNOBSERVED (albedo null) so the neutral treatment stays reachable
  // offline. Corner winding fronts the room interior.
  shell: {
    shell_version: 2,
    scene_id: MOCK_READY_SCENE_ID,
    status: "ready",
    reason: null,
    method: "arkit_planes",
    floor: {
      polygon: [
        [-2.2, 0, 1.4],
        [0.6, 0, 1.4],
        [0.6, 0, 0.9],
        [1.8, 0, 0.9],
        [1.8, 0, -2.6],
        [-2.2, 0, -2.6],
      ],
      measured_polygon: [
        [-2.1, 0, 1.3],
        [0.6, 0, 1.3],
        [0.6, 0, 0.9],
        [1.7, 0, 0.9],
        [1.7, 0, -2.5],
        [-2.1, 0, -2.5],
      ],
      y: 0,
      provenance: {
        edges: [
          "observed",
          "observed",
          "observed",
          "extended_to_wall:wall_00",
          "extended_to_wall:wall_01",
          "observed",
        ],
      },
      material: mockMaterial("wood", "#8a6f52", 0.6, 0.62),
    },
    walls: [
      {
        wall_id: "wall_00",
        quad: [
          [-2.2, 0, -2.6],
          [1.8, 0, -2.6],
          [1.8, 2.2, -2.6],
          [-2.2, 2.2, -2.6],
        ],
        measured_quad: [
          [-2.2, 0.3, -2.6],
          [1.8, 0.3, -2.6],
          [1.8, 2.2, -2.6],
          [-2.2, 2.2, -2.6],
        ],
        edges: {
          bottom: { state: "extended_to_floor", extension_m: 0.3 },
          top: { state: "observed", extension_m: 0 },
          left: { state: "observed", extension_m: 0 },
          right: { state: "extended_to_wall:wall_01", extension_m: 0.2 },
        },
        openings: [
          {
            classification: "door",
            rect_uv: [
              [0.62, 0],
              [0.84, 0.86],
            ],
          },
        ],
        classification: "wall",
        material: mockMaterial("painted", "#c9b9a4", 0.85, 0.55),
      },
      {
        wall_id: "wall_01",
        quad: [
          [-2.2, 0, 1.4],
          [-2.2, 0, -2.6],
          [-2.2, 2.2, -2.6],
          [-2.2, 2.2, 1.4],
        ],
        measured_quad: [
          [-2.2, 0, 1.4],
          [-2.2, 0, -2.6],
          [-2.2, 2.2, -2.6],
          [-2.2, 2.2, 1.4],
        ],
        edges: {
          bottom: { state: "observed", extension_m: 0 },
          top: { state: "observed", extension_m: 0 },
          left: { state: "observed", extension_m: 0 },
          right: { state: "observed", extension_m: 0 },
        },
        openings: [],
        classification: null,
        material: mockMaterial(null, null, 0.9, 0.04),
      },
    ],
    quality: {
      planes_in_bundle: 4,
      frames_used: 9,
      material_version: 1,
      fragments_dropped: 1,
    },
  },
  asset_urls: {
    [GS("sofa")]: "/dev-fixtures/sofa.ply",
    [GS("table")]: "/dev-fixtures/table.ply",
    [GS("lamp")]: "/dev-fixtures/lamp.ply",
  },
  expires_at: new Date(Date.now() + 3600_000).toISOString(),
};

const LATENCY_MS = 250;

function delay<T>(value: T): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), LATENCY_MS));
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Canned guest replies, grounded in the fixture manifest above (sofa /
 * table / lamp placed; the plant seen but never placed). Beat + invitation
 * shape; the one distance quoted (about 1.2 m sofa↔table centers) is the
 * fixture's real center-to-center distance, honestly rounded.
 */
function mockGuestReply(text: string): string {
  const q = text.toLowerCase();
  if (q.includes("plant")) {
    return (
      "The plant I only glimpsed — it never held still in the scan long " +
      "enough to place, so I honestly can't say where it stands. The sofa, " +
      "table, and lamp I can speak to properly. Want to start with one of those?"
    );
  }
  if (/(colou?r|material|fabric|light|bright|window)/.test(q)) {
    return (
      "I can't see color or light yet — this room reached me as shapes and " +
      "positions, not surfaces. I'd rather admit that than guess. I can tell " +
      "you how the pieces sit around each other, if that helps?"
    );
  }
  if (/(move|rearrange|swap|push|put the|redecorate)/.test(q)) {
    return (
      "I can't move things yet — today I have eyes, not hands. What I can " +
      "do is talk through how the room sits right now, so when moving day " +
      "comes we both know what we're working with. Shall we?"
    );
  }
  if (/(far|distance|close|apart|between)/.test(q)) {
    return (
      "About 1.2 m between the sofa's center and the table's center — of " +
      "everything placed, they're each other's nearest neighbors, so that " +
      "corner already works as one sitting place. Want the lamp's corner too?"
    );
  }
  return (
    "Three pieces stand placed — the sofa anchoring one end, the table in " +
    "close company, the lamp keeping its own corner. The plant I saw but " +
    "couldn't place. Where would you like to start?"
  );
}

export class MockApiClient implements ApiClient {
  readonly scenes = STATUS_FIXTURES.map((f, i) => sceneFixture(i, f.status, f.minutesAgo));

  async listScenes(limit = 50): Promise<SceneSummary[]> {
    const sorted = [...this.scenes].sort((a, b) =>
      b.created_at.localeCompare(a.created_at),
    );
    return delay(sorted.slice(0, limit));
  }

  async getSceneByBundle(bundleId: string): Promise<SceneSummary> {
    const scene = this.scenes.find((s) => s.bundle_id === bundleId);
    if (!scene) {
      throw new ApiError(404, "not_found", `No scene for bundle ${bundleId}`);
    }
    return delay(scene);
  }

  async getSceneAssets(sceneId: string): Promise<SceneAssets> {
    const scene = this.scenes.find((s) => s.scene_id === sceneId);
    if (!scene) {
      throw new ApiError(404, "not_found", `No scene ${sceneId}`);
    }
    if (scene.status !== "ready") {
      throw new SceneNotReadyError(scene.status);
    }
    return delay(READY_ASSETS);
  }

  // ── Conversation (decision 0058): accumulating in-memory transcript ──────
  // Starts empty so first-sight is reachable; resets on reload (instance
  // state). Trigger phrases walk every composer state offline:
  //   !error    — in-stream terminal error event after a few deltas
  //   !budget   — pre-stream 429 (rested; lifts after ~30 s here)
  //   !slow     — long inter-delta gaps (watch pings/batching behavior)
  //   !inflight — pre-stream 409; a pretend other-tab turn lands ~4 s later
  private conversation: ConversationTurn[] = [];

  private requireReady(sceneId: string): void {
    const scene = this.scenes.find((s) => s.scene_id === sceneId);
    if (!scene) throw new ApiError(404, "not_found", `No scene ${sceneId}`);
    if (scene.status !== "ready") throw new SceneNotReadyError(scene.status);
  }

  async getConversation(sceneId: string): Promise<ConversationSnapshot> {
    this.requireReady(sceneId);
    return delay({
      conversation: {
        scene_id: sceneId,
        turn_count: this.conversation.length,
        rested_until: null,
      },
      turns: [...this.conversation.slice(-50)],
      cursor: null,
    });
  }

  private appendTurn(text: string, reply: string, clientMsgId: string): ConversationTurn {
    const turn: ConversationTurn = {
      turn_index: this.conversation.length,
      client_msg_id: clientMsgId,
      user_text: text,
      assistant_text: reply,
      created_at: new Date().toISOString(),
    };
    this.conversation.push(turn);
    return turn;
  }

  async sendMessage(
    sceneId: string,
    text: string,
    clientMsgId: string,
  ): Promise<AsyncIterable<GuestEvent>> {
    this.requireReady(sceneId);
    await sleep(LATENCY_MS);

    if (text.includes("!budget")) {
      throw new BudgetExhaustedError(
        "We've talked a lot today, and I want to keep doing right by this " +
          "room — let's pick it up again a little later.",
        new Date(Date.now() + 30_000).toISOString(),
      );
    }
    if (text.includes("!inflight")) {
      // Simulate the second-tab race: throw 409 now, land the "other
      // tab's" turn shortly after so the blocked state resolves.
      setTimeout(() => {
        this.appendTurn(
          "(from your other window)",
          "That corner reads well from here — the lamp keeps it from going quiet.",
          crypto.randomUUID(),
        );
      }, 4_000);
      throw new TurnInFlightError();
    }

    // Dedupe replay parity with the server: a known client_msg_id streams
    // the stored turn back, never regenerates.
    const existing = this.conversation.find((t) => t.client_msg_id === clientMsgId);
    const slow = text.includes("!slow");
    const errorMid = text.includes("!error");
    const reply = existing?.assistant_text ?? mockGuestReply(text);
    const appendTurn = () => this.appendTurn(text, reply, clientMsgId);

    async function* stream(): AsyncGenerator<GuestEvent> {
      if (existing) {
        yield { type: "delta", text: existing.assistant_text };
        yield { type: "done", turn: existing };
        return;
      }
      const words = reply.split(" ");
      for (let i = 0; i < words.length; i++) {
        await sleep(slow ? 500 : 45);
        if (errorMid && i === Math.min(5, words.length - 1)) {
          yield { type: "error", code: "model_error" };
          return;
        }
        yield { type: "delta", text: (i > 0 ? " " : "") + words[i] };
      }
      yield { type: "done", turn: appendTurn() };
    }
    return stream();
  }
}
