// Generated by tools/gen_mark.py. Do not edit; edit the generator.
//
// The product mark's geometry, in a 1024x1024 design space. Consumed by
// DesignSystem/Wordmark.swift. See tools/gen_mark.py for the construction and
// for why the mark is a fill rather than a stroke.

import CoreGraphics

enum MarkGeometry {
    /// The design space the points below are expressed in.
    static let canvas: CGFloat = 1024

    /// Ink plate for a mark on a LIGHT field -- the rim band shows.
    static let plateFramed: [CGPoint] = [CGPoint(x: 512.00, y: 132.00), CGPoint(x: 841.09, y: 322.00), CGPoint(x: 841.09, y: 702.00), CGPoint(x: 512.00, y: 892.00), CGPoint(x: 182.91, y: 702.00), CGPoint(x: 182.91, y: 322.00)]

    /// Ink plate for a mark on a DARK field -- only the seams show.
    static let plateFrameless: [CGPoint] = [CGPoint(x: 512.00, y: 210.52), CGPoint(x: 773.09, y: 361.26), CGPoint(x: 773.09, y: 662.74), CGPoint(x: 512.00, y: 813.48), CGPoint(x: 250.91, y: 662.74), CGPoint(x: 250.91, y: 361.26)]

    /// Right wall, left wall, floor. Identical under either plate.
    static let faces: [[CGPoint]] = [
        [CGPoint(x: 537.20, y: 497.45), CGPoint(x: 537.20, y: 225.07), CGPoint(x: 773.09, y: 361.26), CGPoint(x: 773.09, y: 633.64)],
        [CGPoint(x: 486.80, y: 497.45), CGPoint(x: 250.91, y: 633.64), CGPoint(x: 250.91, y: 361.26), CGPoint(x: 486.80, y: 225.07)],
        [CGPoint(x: 512.00, y: 541.10), CGPoint(x: 747.89, y: 677.29), CGPoint(x: 512.00, y: 813.48), CGPoint(x: 276.11, y: 677.29)],
    ]
}
