// Generated by tools/gen_mark.py. Do not edit; edit the generator.
//
// The product mark's geometry, in a 1024x1024 design space. Consumed by
// DesignSystem/Wordmark.swift. See tools/gen_mark.py for the construction and
// for why the mark is never set beside the wordmark.
//
// Emitted as ellipse PARAMETERS rather than as path data, because the splash
// screen animates the wordmark's "oo" into this mark by interpolating these
// five numbers. Path data would have to be re-derived to do that.

import CoreGraphics

/// One ellipse of the mark, in the generated design space.
struct MarkEllipse {
    let cx: CGFloat
    let cy: CGFloat
    let a: CGFloat
    let b: CGFloat
}

/// One ring: the band between two concentric ellipses. Fill it EVEN-ODD.
struct MarkRing {
    let outer: MarkEllipse
    let inner: MarkEllipse
}

enum MarkGeometry {
    /// The design space the values below are expressed in.
    static let canvas: CGFloat = 1024

    /// How far both rings lean back, in degrees.
    static let tiltDegrees: CGFloat = -35.0

    /// The two interlocking rings, left then right.
    static let rings: [MarkRing] = [
        MarkRing(outer: MarkEllipse(cx: 349.29, cy: 512.00, a: 323.01, b: 235.90), inner: MarkEllipse(cx: 349.29, cy: 512.00, a: 281.78, b: 194.66)),
        MarkRing(outer: MarkEllipse(cx: 674.71, cy: 512.00, a: 323.01, b: 235.90), inner: MarkEllipse(cx: 674.71, cy: 512.00, a: 281.78, b: 194.66)),
    ]

    /// The mark's own ink bounds in the design space -- what clear space
    /// (0.5 H on every side) and the minimum sizes are measured from.
    static let inkWidth: CGFloat = 919.79
    static let inkHeight: CGFloat = 535.41
}
