"use client";

/**
 * The splat viewer page. Three ways in, all funneling into the same
 * PositionedSplat list that SplatViewer renders:
 *
 *   /viewer?scene=<scene_id> — the product path: fetch the scene's assets
 *       (manifest v2 + signed URLs) and render the fused, placed objects
 *       as one assembled room.
 *   /viewer?url=<splat url>  — dev: render a single splat file at origin.
 *   drag & drop a .ply/.spz/.splat/.ksplat file — dev: same, from disk.
 *
 * With no source given it tries /dev-fixtures/manifest.json (the local
 * synthetic room generated by tools/make_synthetic_splat.py) and falls
 * back to an instructions panel.
 */

import { useSearchParams } from "next/navigation";
import { Suspense, useCallback, useEffect, useState } from "react";

import SplatViewer from "@/components/SplatViewer";
import { getApiClient } from "@/lib/api";
import { ApiError, SceneNotReadyError } from "@/lib/api/client";
import {
  assembleScene,
  type FusedObject,
  type PositionedSplat,
  type SceneAssets,
} from "@/lib/api/types";
import { statusMeta } from "@/lib/status";

/** Async-only result, stamped with the source key it was loaded for —
 * a stale key renders as loading, so effects never set state
 * synchronously (react-hooks/set-state-in-effect). */
type Result =
  | { key: string; phase: "idle" } // no source; show instructions
  | { key: string; phase: "not_ready"; message: string }
  | { key: string; phase: "error"; message: string }
  | {
      key: string;
      phase: "ready";
      splats: PositionedSplat[];
      unrenderable: FusedObject[];
    };

function singleSplat(key: string, url: string, label: string): Result {
  return {
    key,
    phase: "ready",
    unrenderable: [],
    splats: [
      { url, label, position: [0, 0.5, 0], rotation_xyzw: [0, 0, 0, 1], scale: 1 },
    ],
  };
}

function ViewerContent() {
  const params = useSearchParams();
  const sceneId = params.get("scene");
  const directUrl = params.get("url");
  const key = `${sceneId ?? ""}|${directUrl ?? ""}`;
  const [result, setResult] = useState<Result | null>(null);

  // Drag-drop overrides the URL-derived source; it stamps the current key
  // so it stays visible until the params actually change.
  const state: Result | { phase: "loading" } =
    result && result.key === key ? result : { phase: "loading" };

  useEffect(() => {
    let cancelled = false;

    async function load() {
      if (directUrl) {
        setResult(singleSplat(key, directUrl, "splat"));
        return;
      }
      if (sceneId) {
        try {
          const assets = await getApiClient().getSceneAssets(sceneId);
          if (cancelled) return;
          const { splats, unrenderable } = assembleScene(assets);
          setResult({ key, phase: "ready", splats, unrenderable });
        } catch (exc: unknown) {
          if (cancelled) return;
          if (exc instanceof SceneNotReadyError) {
            setResult({
              key,
              phase: "not_ready",
              message: statusMeta(exc.sceneStatus).description,
            });
          } else {
            setResult({
              key,
              phase: "error",
              message:
                exc instanceof ApiError ? exc.message : "Could not load the scene.",
            });
          }
        }
        return;
      }
      // No source: try the local dev fixture manifest.
      try {
        const resp = await fetch("/dev-fixtures/manifest.json");
        if (!resp.ok) throw new Error("no fixture");
        const assets = (await resp.json()) as SceneAssets;
        if (cancelled) return;
        const { splats, unrenderable } = assembleScene(assets);
        setResult(
          splats.length
            ? { key, phase: "ready", splats, unrenderable }
            : { key, phase: "idle" },
        );
      } catch {
        if (!cancelled) setResult({ key, phase: "idle" });
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, [key, sceneId, directUrl]);

  const onDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      const file = e.dataTransfer.files[0];
      if (!file) return;
      setResult(singleSplat(key, URL.createObjectURL(file), file.name));
    },
    [key],
  );

  return (
    <div onDrop={onDrop} onDragOver={(e) => e.preventDefault()}>
      <div className="flex items-baseline justify-between">
        <h1 className="text-2xl font-semibold tracking-tight">Viewer</h1>
        {state.phase === "ready" && (
          <span className="text-sm text-zinc-500">
            {state.splats.length} object{state.splats.length === 1 ? "" : "s"}
            {state.unrenderable.length > 0 &&
              ` · ${state.unrenderable.length} unplaced`}
          </span>
        )}
      </div>

      {state.phase === "loading" && (
        <div className="mt-6 h-[60vh] animate-pulse rounded-xl border border-zinc-800 bg-zinc-900/40" />
      )}

      {state.phase === "idle" && (
        <div className="mt-6 flex h-[60vh] flex-col items-center justify-center rounded-xl border border-dashed border-zinc-700 bg-zinc-900/30 text-center">
          <p className="text-zinc-300">Drop a splat file to view it</p>
          <p className="mt-2 max-w-sm text-sm text-zinc-500">
            .ply, .spz, .splat or .ksplat — or open a ready scene from{" "}
            <a href="/scenes" className="text-sky-400 hover:underline">
              your scenes
            </a>
            . (Dev fixture: run <code>tools/make_synthetic_splat.py</code>.)
          </p>
        </div>
      )}

      {state.phase === "not_ready" && (
        <div className="mt-6 rounded-xl border border-sky-500/20 bg-sky-500/5 p-6">
          <p className="text-sm font-medium text-sky-300">Not ready yet</p>
          <p className="mt-1 text-sm text-zinc-400">{state.message}</p>
        </div>
      )}

      {state.phase === "error" && (
        <div className="mt-6 rounded-xl border border-red-500/20 bg-red-500/5 p-6">
          <p className="text-sm font-medium text-red-300">Couldn&apos;t open the scene</p>
          <p className="mt-1 text-sm text-zinc-400">{state.message}</p>
        </div>
      )}

      {state.phase === "ready" && (
        <>
          <SplatViewer splats={state.splats} className="mt-6 h-[60vh]" />
          {state.unrenderable.length > 0 && (
            <p className="mt-3 text-sm text-zinc-500">
              Not shown:{" "}
              {state.unrenderable
                .map((o) => `${o.label} (${o.reason ?? "no transform"})`)
                .join(", ")}
            </p>
          )}
        </>
      )}
    </div>
  );
}

export default function ViewerPage() {
  return (
    <Suspense
      fallback={<div className="mt-6 h-[60vh] animate-pulse rounded-xl bg-zinc-900/40" />}
    >
      <ViewerContent />
    </Suspense>
  );
}
