// Generated by tools/gen_mark.py. Do not edit; edit the generator.
//
// The product mark's geometry, in a 0 0 1024 1024 viewBox. Consumed by
// components/Wordmark.tsx. See tools/gen_mark.py for the construction and for
// why the mark is a fill rather than a stroke.

/** Ink plate for a mark sitting on a LIGHT field -- the rim band shows. */
export const PLATE_FRAMED = "M512 132 841.09 322 841.09 702 512 892 182.91 702 182.91 322Z";

/** Ink plate for a mark sitting on a DARK field -- only the seams show. */
export const PLATE_FRAMELESS = "M512 210.52 773.09 361.26 773.09 662.74 512 813.48 250.91 662.74 250.91 361.26Z";

/** Right wall, left wall, floor. Identical under either plate. */
export const FACES = [
  "M537.2 497.45 537.2 225.07 773.09 361.26 773.09 633.64Z",
  "M486.8 497.45 250.91 633.64 250.91 361.26 486.8 225.07Z",
  "M512 541.1 747.89 677.29 512 813.48 276.11 677.29Z",
] as const;

/** Absolute mark colours. These never inherit from surrounding text. */
export const MARK_INK = "#3a2d22";
export const MARK_WALL = "#f7efdf";
export const MARK_FLOOR = "#8e3b2f";
