// Generated by tools/gen_mark.py. Do not edit; edit the generator.
//
// The product mark's geometry. Consumed by components/Wordmark.tsx. See
// tools/gen_mark.py for the construction, for why the mark is a pair of filled
// rings rather than a stroke, and for why it is never set beside the wordmark.

/** The two rings. Each is ONE path and MUST be filled even-odd, or its
 * interior stops being a hole and the interlock is lost. */
export const MARK_RINGS = [
  "M613.89 326.73C688.61 433.45 630.73 602.91 484.59 705.23C338.46 807.56 159.42 803.99 84.69 697.27C9.97 590.55 67.85 421.09 213.99 318.77C360.12 216.44 539.16 220.01 613.89 326.73ZM580.11 350.37C641.78 438.44 588.43 582.2 460.95 671.46C333.46 760.72 180.13 761.69 118.47 673.63C56.8 585.56 110.15 441.8 237.63 352.54C365.12 263.28 518.45 262.31 580.11 350.37Z",
  "M939.31 326.73C1014.03 433.45 956.15 602.91 810.01 705.23C663.88 807.56 484.84 803.99 410.11 697.27C335.39 590.55 393.27 421.09 539.41 318.77C685.54 216.44 864.58 220.01 939.31 326.73ZM905.53 350.37C967.2 438.44 913.85 582.2 786.37 671.46C658.88 760.72 505.55 761.69 443.89 673.63C382.22 585.56 435.57 441.8 563.05 352.54C690.54 263.28 843.87 262.31 905.53 350.37Z",
] as const;

/** The mark's own ink bounds inside the 1024 design space the paths above are
 * authored in. A caller sizes the DRAWING with these rather than a square
 * canvas that is 48% empty. A canvas painter needs the numbers; SVG needs the
 * viewBox below. */
export const MARK_INK_BOX = {
  x: 52.10,
  y: 244.30,
  w: 919.79,
  h: 535.41,
} as const;

/** `MARK_INK_BOX` as an SVG viewBox, cropping the design space to the ink. */
export const MARK_VIEWBOX =
  `${MARK_INK_BOX.x} ${MARK_INK_BOX.y} ${MARK_INK_BOX.w} ${MARK_INK_BOX.h}`;

/** Ink width ÷ ink height. Size the mark by HEIGHT and derive width from this
 * — the design file's minimum sizes are all stated in terms of height. */
export const MARK_ASPECT = 1.7179;

/** Absolute mark colours. These never inherit from surrounding text. */
export const MARK_INK = "#c04d3e";
/** The mark when it sits ON terracotta rather than beside it. */
export const MARK_REVERSE = "#fbf5f2";
